### ISSUE TITLE
About the Connections folder

### ISSUE THREAD

**Issue by matthew-mx** [NVlabs/matchlib#11]
Hello!
I notice the connections folder is removed from the main branch, but files like nvhls_marshaller.h still include them. Is the main branch compatible with the connections folder in the hybrid_router branch? Or if not, if there is a usable version of such files. Thanks

**Comment by npfet** [comment]
Hi Matt,

Connections is now maintained by Siemens EDA (and bundled with Catapult), and is available here: https://github.com/hlslibs/matchlib_connections

We haven't tried the connections version in the hybrid_router branch in a long time, so I'm not sure if current main branch HEAD would still work with that version of connections.

Best regards,

Nate

**Comment by npfet** [comment]
I'm not quite following- What tool version are you referring? Thanks, Nate

**Comment by npfet** [comment]
Hi @matthew-mx,

Are you sure that SystemC 2.3.1 doesn't have tlm.h? If I check the official SystemC 2.3.1 release by Accelera (https://www.accellera.org/downloads/standards/systemc/files), I do see that tlm.h is included at "systemc-2.3.1/src/tlm.h". Be sure to download the 2.3.1 link that says "Includes TLM". I haven't tried a newer release, so I can't comment on what sort of compatibility it will have with the newer version.

Thanks,

Nate

**Comment by ben-k** [comment]
Closing this as resolved, since we didn't get any further questions.  If you are still having problems feel free to re-open or file a new issue.
