### ISSUE TITLE
Multiple problems with ArbitratedScratchpad.h

### ISSUE THREAD

**Issue by ttambe** [NVlabs/matchlib#6]
Hi,

I am currently seeing two bugs in ArbitratedScratchpad.h.

1. When `NumBanks` is 1, the operation becomes incorrect. I was able to easily fix this bug by replacing [L65-L66](https://github.com/NVlabs/matchlib/blob/main/cmod/include/ArbitratedScratchpad.h#L65-L66) with the edits  below: 
```
  static const int log2_nbanks = (NumBanks == 1) ? 1 : nvhls::nbits<NumBanks - 1>::val;
  static const int log2_inputs = (NumInputs == 1) ? 1 : nvhls::nbits<NumInputs - 1>::val;
```
2. When `NumBanks` is not a power of 2 (e.g., 3 or 6), the read operation is incorrect in some corner cases. For example with `NumBanks` = 3,  reading address 0x3 returns an invalid response (i.e., load_rsp.valids = 0).  Can you please help looking into this issue?

Thanks,
-Thierry

**Comment by ttambe** [comment]
Regarding 2) I traced the problem back to the compute_bank_request() function inside ArbitratedScratchpad.h on [L120-L121](https://github.com/NVlabs/matchlib/blob/main/cmod/include/ArbitratedScratchpad.h#L120-L121). This bank selection only works when `NumBanks` is a power of 2.

**Comment by ttambe** [comment]
It seems like the only way to support a scratchpad with a `NumBanks` that is odd or not a power-of-2, is to use the modulus and division operators to compute the bank selection and the local bank address, respectively.

I made this change inside the compute_bank_request() function and the scratchpad's post-HLS cycle behavior is still one clock cycle at 1GHz as in the original design. The only overhead of using mod/div is a slight increase in area and power. I used Catapult v2021.1-950854 which, apparently, includes some optimizations on the mod/div operations.

**Comment by ben-k** [comment]
Thanks Thierry!  Could you submit (two separate) pull requests for these changes so we can review and merge them?  Example instructions are [here](https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/) in case you are unfamiliar with this process.

Probably we would want compute_bank_request() to keep the current behavior NumBanks is a power of 2, and only instantiate the divider in the non-power-of-2 case.

**Comment by ttambe** [comment]
Hi Ben,
I created 2 pull requests addressing these 2 issues. Merging the fix to the 2nd issue might be a bit tricky. I explained it in the comment.

**Comment by ben-k** [comment]
The changes from the PRs have been merged in, so closing.

**Comment by ttambe** [comment]
Thank you Ben!
